resume: 
pretrain:
hard_prompt_pretrain: 
seed: 1024
data:
    dataset: k400
    modality: video
    num_segments: 32
    seg_length: 1
    batch_size: 8
    workers: 4
    num_classes: 200
    image_tmpl: 'img_{:05d}.jpg'
    train_root: 'kinetics400/videos_train/'
    train_list: 'kinetics400/annotations/k400_splits/fs_base_s1_train_new.txt'
    val_root: 'kinetics400/videos_val/' 
    val_list: 'kinetics400/annotations/k400_splits/base_val_new.txt'
    label_list: 'lists/labels/kinetics_400_base_labels.csv'  
    input_size: 224
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    arch_vanilla: ViT-B/16 #ViT-B/32 ViT-B/16
    init: True
    tm: False  # False tsm tokent1d tokenshift
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_k400
    sim_header: None  # Transf 
    interaction: DPS 
    joint_st: False
    drop: 0          
    freeze: P # V:Vision T:Text V+T: Vision+Text P:Prompt
    gaa: True # use generic attributes anchor
prompt:
    use_hard_prompt: True
    trainer_type: 'IVLP'
    vision_depth: 9    
    vision_ctx: 16        
    language_depth: 9
    language_ctx: 16
    gaa_train_root: "gaa/video/" 
    gaa_train_list: "datasets_splits/base2novel_splits/gaa_splits/fs_base_gaa_train.txt"
    gaa_label: 'lists/labels/gaa_base_labels_n.csv'
    dropout: 0.5 
solver:
    type: cosine
    epochs: 12 #12 30
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 4.e-2 
    lr_warmup_step: 2 
    weight_decay: 0.001 
    loss_type: CE 
    evaluate: False
    clip_ratio: 1.0 
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1
    skip_epoch: [1,2,3,4,5,6] 