pretrain: k400-vitb.pt #exp_nce/k400/ViT-B/16/20250627_130403/model_best.pt  #'exp_nce/b2k400/model_best.pt'
hard_prompt_pretrain: 'exp_nce/k400_base_pre/model_best.pt'  #'exp_nce/k600_100/model_best.pt' #'exp_nce/ucf_base_pre/model_best.pt'  
resume:
seed: 1024
data:
    dataset: hmdb51
    modality: video #RGB
    num_segments: 32
    seg_length: 1
    batch_size: 8
    workers: 4
    num_classes: 25
    image_tmpl: 'img_{:05d}.jpg'
    train_root: 'hmdb51/video1/'
    train_list: 'datasets_splits/base2novel_splits/hmdb_splits/fs_base_s1_train.txt'
    val_root: 'hmdb51/video1/'
    #val_list: 'datasets_splits/base2novel_splits/hmdb_splits/novel_val.txt'
    val_list: 'datasets_splits/base2novel_splits/hmdb_splits/base_val.txt'
    label_list: 'lists/labels/hmdb_51_base_labels.csv'
    #label_list: 'lists/labels/hmdb_51_novel_labels.csv'
    input_size: 224

    random_shift: True
network:
    arch: ViT-B/16  #ViT-B/32 ViT-B/16
    arch_vanilla: ViT-B/16 #ViT-B/32 ViT-B/16
    init: True
    tm: False  # False tsm tokent1d tokenshift
    drop_out: 0.0 
    emb_dropout: 0.0 
    type: clip_hmdb
    sim_header: None     # Transf   None  
    interaction: DPS  # DP VCS
    joint_st: False
    drop: 0          
    freeze: P # V:vision T:Text V+T: vision+text P:prompt
    gaa: True # use generic attributes anchor
prompt:
    use_hard_prompt: True
    trainer_type: 'IVLP'
    vision_depth: 9    
    vision_ctx: 16        
    language_depth: 9
    language_ctx: 16
    gaa_train_root: "gaa/video/" 
    gaa_train_list: "datasets_splits/base2novel_splits/gaa_splits/fs_base_gaa_train.txt"
    gaa_label: 'lists/labels/gaa_base_labels_n.csv'
    dropout: 0.5 

solver:
    type: cosine
    epochs: 12
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 4.e-2
    lr_warmup_step: 2
    weight_decay: 0.001
    loss_type: CE
    evaluate: False
    clip_ratio: 0.1 #0.1
    grad_accumulation_steps: 1
logging:
    print_freq: 10
    eval_freq: 1
    skip_epoch: [1,2,3,4,5,6]